# Generated by Django 2.1.7 on 2019-03-30 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='título')),
                ('anotacoes', models.TextField()),
                ('privado', models.BooleanField(blank=True, null=True)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agenda Particular',
                'verbose_name_plural': 'Agenda Particular',
            },
        ),
        migrations.CreateModel(
            name='Agenda_Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='título')),
                ('anotacoes', models.TextField()),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agenda Institucional',
                'verbose_name_plural': 'Agenda Institucional',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('telefone_celular', models.CharField(blank=True, help_text='Número do telefone ceular no formato (99) 99999-9999', max_length=15, null=True, verbose_name='Telefone ceular')),
                ('telefone_fixo', models.CharField(blank=True, help_text='Número do telefone fixo no formato (99) 9999-9999', max_length=14, null=True, verbose_name='Telefone fixo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='agenda_global',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agenda.Pessoa'),
        ),
    ]
