# Generated by Django 2.1.7 on 2019-03-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0002_agenda_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda_global',
            name='privado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
