# Generated by Django 2.1.7 on 2019-03-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0003_agenda_global_privado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda_global',
            name='autor',
        ),
    ]
