# Generated by Django 2.1.7 on 2019-03-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0004_remove_agenda_global_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='privado',
            new_name='publica',
        ),
        migrations.RenameField(
            model_name='agenda_global',
            old_name='privado',
            new_name='publica',
        ),
    ]
